matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: SNNo6ww0rtgbBCpoP0g0PcVdvyGmpdj35p19SDkjPLNZ8XXqIO3wytr/+aomWC0MrqjRrPhSfDx7ZkV7BseWNWhTs+ZGGgsP1mfq/sYqCRgnLssqLRD/Jn9TB/SITACaCyesjRUS6RVfaFpLeCaDA4qflo1EaFGtt0WXtsz640PvrEM6HRVY3cTHfwatWrn17EsIOdu/Dh37hbu5HtGVpI2q6Mz9f44Sq3LsAUUPvjz4yibG7dIvup4YsQ+KBjmRZo0OvmCHv/+GG28avG4xnIilgdOX8HmuUQgAGjUFoDCcF0njWZtOedodRQXHbjTd63RRGusC2/kAnwTYhy336wVOeT7fBgW0iV9nrPh0kHoIOPnGNbmi3FWDxvwtFVT/17LwQWKYIJ+cNfmtH/S0mGzBdD1g8bJdl8crny1TYNDCPvv+HQVxf7R9Z3jZVh7MR03VYs357vJUHQRrUo8MirmYiseIRfp+PlnUbdIln/W2XuWTM1Erfsx9YnUmLmy6Zy4iXcWKqhupVoAYd+Utbz5VAwzB3CrYSUO5q6fSqjc6QoDbWAsSJLomF01pxXD8SvafzIMd3MG5Jvjw97Mx1OoOwt1OGBq5qVdmDiuD1/SzFzYzqjPRbFB5wg+KxQB3gS8lIZuVrF8s2CAFXVbxrI+LciUehzSyq7VfRbvp8Sw=
        app: project-boilerplate
