matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: IGnKzdJx1HX3i3ZzZjZCbsNcstRO7QF4no5Sb/R5lQz/5eMQxzP2etahDX++6JUYLokccGaN5SfmmBO9PSg+Bq8vncryuf2MK7aFROn/olqIjh6BWG38x7LD8WwgTtdkYazZHkN4+9quA5YoNMLgaKu4fw77EZozEiIJD4CU7+ciIE+8Gf1r6hsVo511ca+xvTyKDtWGrjJ12qTav08ZM8BaL4lKAMle+ZZ+XoOQLpx7R5F5aa/QKpEmsNB82AIiFcf8CL2Q84I7n56f4wnKvi4BfFR8TTQVqTU1M3SGOeY6xPUuHCOfjoj2dctCskdt1oD/pHdqRdkPodqn1e13n1wXvF+QRBFUBN7TSaiosl6fJL2bUteA/9HDaiTBVawPjOmJ+1jZOUT9DyPvVNXtPszH/jEk2LOchOe6T7uKShXTFZ/x6xNnaxZLUAYIzQ2IfJI7LLBg8OVgRB8xXnD7PkZNWvR65q+PCTtTctYwe891DIzb3HusIJac9W8u/+MWQPcNU18oztxA+388PYJs+5gMhDKx+oNQ2+y5pP9ILkaZ0b+vO3RgF/f97aqxGqAAfzrdMX/t5bFVtk0zx2blbrNzzcqVHijR6VT2NkodAGqubM/cL6LHSs4HWYzi3RgGU1x28TlJvNbakwopqj9GKkr4Hp2pAzdNmfPyS19uPcM=
        app: project-boilerplate
