matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: fWG7j4HI4XukuQF86curGdaRYbpDceRxZfDJ3svUF6UB1V9fFxPCgoDd5RXk8pd5sxzKpcSFP042DTqdfNL1FiP3PnBmqx7kbuk4Rp+slqBvB9wqFShhI6qFxEXlRkQ2a2BsjcNP6FN/bl+dg1E18nZ+sinlrJdLI6b5tSgBbg6DRwuyD52GGEx7Cnws0G5lvwswiDnrPTBMB+5OxrQ5zGNjYynqJbCYDBmXSccxVX8iijDEFClnqNeTdnHFcysyoFx5zFVvyoUhOG+IEmEiU0/hjMXklWuzqyY0W9bR1iWMZ4BgSVRYowL6OCyKOGQNR+fn26veOU7kO/cRpiAKhHLVoG1kFzD7DBwICRSYaOybiNLofxhmDmqGqfFiWrWWEQHNpm7NX7ZSVyy9I/+BN5Kw9aETlLgGVAoGbW0jJAdYCdEVczdWZMpq51424317vnSDrMK9x8F/aVcibIO1iIZA7T6IV7L6CXWOy7sXreZ/dTgPyCqT8G38GBvGM06ASoragwueW5P9VxVgIhcwBY82voARJE/W/Rn0T3Lbr4R4VSgQjaqnJE8Ul+uuBmgwZlWxoG4hp8hS1iezR88zDpkc8pmDUKWWppul6b/vmRlasQJtqu6OGxi0iuhGyIkTcJ3ehNCijqUz4FBF/fE5kC+xwpHdsR3YpCFTfJruBz8=
        app: project-boilerplate
